### ISSUE TITLE
Call to undefined function Aceraven777\PayMaya\API\array_only()

### ISSUE THREAD

**Issue by NikkoJaca** [aceraven777/laravel-paymaya#10]
Hello.

While currently exploring your package, I've encountered an error regarding the `array_only()` function helper of Laravel when executing your sample code for Refund Payment.

I'm using Laravel 6 and this function helper (along with others related to it) are now deprecated since Laravel 5.8. [See this pull request from Laravel.](https://github.com/laravel/framework/pull/26898)

The concerning code is at line 29 of RefundPayment.php. My suggestion is to replace `array_only()` with `Arr::only()` and import the `Illuminate\Support\Arr` which comes with Laravel.

But I haven't tested this for pre-5.8 so I suppose if we we're to replace the deprecated code means this change will make your package only support Laravel 5.8 and onwards.

Hoping for your positive response!

EDIT: Updated link to the proper pull request.

**Comment by NikkoJaca** [comment]
Upon further investigation, Laravel has compatibility package for these deprecated helpers. 

Please see: [laravel/helpers](https://github.com/laravel/helpers).

The Refund Payment function now did not produce an error upon installation of this package.

However, your package did not specify laravel/helpers as a requirement at installation if using Laravel Framework 5.8 and above.

If you insist to use these deprecated helper functions, you can require this package as part of the composer installation.

EDIT: typo

**Comment by aceraven777** [comment]
Hi @NikkoJaca ,

Thanks for raising this issue, I created a release for this fix **v1.0.6**.

I followed your first suggestion which is to replace `array_on` with `Arr::only`.

**Comment by NikkoJaca** [comment]
Thanks for your rapid feedback!

However, tried to update and test this, and it resulted to errors:

```
Problem 1
    - Installation request for aceraven777/laravel-paymaya ~1.0.6 -> satisfiable by aceraven777/laravel-paymaya[v1.0.6].
    - Conclusion: remove laravel/framework v6.13.1
    - Conclusion: don't install laravel/framework v6.13.1
    - aceraven777/laravel-paymaya v1.0.6 requires illuminate/support ^7.11 -> satisfiable by illuminate/support[7.x-dev, v7.11.0], laravel/framework[7.x-dev].
    - Can only install one of: laravel/framework[7.x-dev, v6.13.1].
    - don't install illuminate/support 7.x-dev|don't install laravel/framework v6.13.1
    - don't install illuminate/support v7.11.0|don't install laravel/framework v6.13.1
    - Installation request for laravel/framework (locked at v6.13.1, required as 6.x.x) -> satisfiable by laravel/framework[v6.13.1].
```

This is due to the `illuminate/support` package needed by `Arr::only` is required in your `composer.json` to version 7.11.0 and above and this would require your package to install Laravel 7.x and above to users (locking the users to Laravel 7 and above) since `illuminate/support` is part of Laravel's packages.

You can change the require entry of `illuminate/support` to 
```
"illuminate/support": "^5.0|^6.0|^7.0"
``` 
so this package could support lower versions of Laravel. 😃

**Comment by aceraven777** [comment]
Hi @NikkoJaca 

I appreciate your effort in testing my package out. :)

I changed the composer to require `"^5.0|^6.0|^7.0"`.

**Comment by NikkoJaca** [comment]
Tested this on Laravel 6 and the composer installation went smooth now! Many thanks! 😄 👍 👍 👍

**Comment by aceraven777** [comment]
Cool! Good to know that somebody is using my package on their projects :)
