### ISSUE TITLE
retrieveRefundInfo is the same with retrieveRefunds?

### ISSUE THREAD

**Issue by NikkoJaca** [aceraven777/laravel-paymaya#12]
Testing out the retrieve refund functions of this package. I noticed that both `retrieveRefundInfo` and `retrieveRefunds` functions outputs the same response:

```
{
   "id":"e5216758-dea9-4957-8006-7c6d5ba5fd68",
   "reason":"Customer unsatisfied.",
   "status":"SUCCESS",
   "createdAt":"2020-05-15T01:36:00.000Z",
   "amount":{
      "currency":"PHP",
      "value":"1.1"
   },
   "checkout":"40396f56-fdc8-45ba-84d6-53654542f723"
},
```

Was the `retrieveRefundInfo` supposed to just get one specific refund info instead of an array of refunds for that checkout payment?

Also noticed that `retrieveRefundInfo`'s function in `RefundPayment.php` is being passed with two arguments: `checkoutId` and `refundId` even though the function itself only expects one which is the `checkoutId`. (This is on line 57 of `retrieveInfo()` function on `RefundPayment.php`).

EDIT: naming conventions

**Comment by aceraven777** [comment]
Hi @NikkoJaca ,

Sorry I don't have time now, I might take a look at this tomorrow, but feel free to make a pull request. :)

**Comment by NikkoJaca** [comment]
All good, I'll try to explore some more stuff and will pull request about this when I discovered something. 😄

**Comment by aceraven777** [comment]
Does your pull request earlier: https://github.com/aceraven777/laravel-paymaya/pull/11 fixes this issue?

**Comment by NikkoJaca** [comment]
Nope, #11 fixes the response array of execute() function in `RefundPayment.php` since it accesses non-existent index `voidId` from PayMaya's Refund API response.

So this issue is more like me trying to understand if the `retrieveRefunds` and `retrieveRefundInfo` are the same since they output same data which is an array of refunds made for that checkout/payment.

At first, I thought `retrieveRefundInfo` is supposed to output only one refund info since the [`retrieveRefundInfo()` that is being called on `RefundPayment.php` is passing two arguments: `checkoutId` and `refundId`](https://github.com/aceraven777/laravel-paymaya/blob/506c4cbe277beee982ef7733cac939ca26bd3902/src/API/RefundPayment.php#L57).

So I thought, with `refundId`, I'll be getting single refund transaction info data. But I found out that the [`retrieveRefundInfo()` being called only requires one argument](https://github.com/aceraven777/laravel-paymaya/blob/506c4cbe277beee982ef7733cac939ca26bd3902/src/Core/CheckoutAPIManager.php#L214).

Maybe the baseURL for `retrieveRefundInfo` should be like this?
```
'/v1/checkouts/'.$checkoutId.'/refunds/'.$refundId
```

But I haven't tested this (and I don't know if this is a valid PayMaya Endpoint URL). Will try to test and get back to you. 😄 

EDIT: formatting, typo, syntax

**Comment by NikkoJaca** [comment]
UPDATE: Yep, the endpoint URL is valid and I was able to fetch one refund transaction info!
```
{
    "success": true,
    "data": {
        "id": "e5216758-dea9-4957-8006-7c6d5ba5fd68",
        "reason": "Customer unsatisfied.",
        "status": "SUCCESS",
        "createdAt": "2020-05-15T01:36:00.000Z",
        "amount": {
            "currency": "PHP",
            "value": "1.1"
        },
        "checkout": "40396f56-fdc8-45ba-84d6-53654542f723"
    },
    "message": "Retrieving refund info successful."
}
```

I'll be creating a pull request shortly. 😸
