### ISSUE TITLE
Invalid authentication credentials.

### ISSUE THREAD

**Issue by kaiserdwight** [aceraven777/laravel-paymaya#15]
The generated keys are working on sandbox environment
but when changed to production it shows this error 
"Invalid authentication credentials. Kindly verify if the key you are using is correct."

**Comment by aceraven777** [comment]
@kdwight , based on the error, the credentials you provided are incorrect. If you're really sure that the keys you've provided are indeed correct, you can raise this issue to your Assigned Account Manager. 

Also when you're calling the `initCheckout` function, make sure the 3rd argument is `PRODUCTION`:
```
PayMayaSDK::getInstance()->initCheckout(
        env('PAYMAYA_PUBLIC_KEY'),
        env('PAYMAYA_SECRET_KEY'),
        'PRODUCTION'
    );
```

**Comment by kaiserdwight** [comment]
@aceraven777 I did put 'PRODUCTION' as 3rd argument and the credentials I used are generated from [paymaya manager](https://manager-sandbox.paymaya.com/) 

am I missing something?

**Comment by aceraven777** [comment]
@kdwight , Are you sure you're putting the public key and secret key in the correct arguments? maybe you accidentally switched them? Did you try hardcoding the production values in the initCheckout? make sure that you're putting the correct values in the arguments

**Comment by aceraven777** [comment]
@kdwight , Wait, I read your first comment:
"The generated keys are working on sandbox environment", so the keys generated on your **paymaya manager** only works on sandbox environment?

There should be a separate keys for your production environment.

**Comment by kaiserdwight** [comment]
Yes, it only works when I put 'SANDBOX' on initCheckout, I generated it from manager-sandbox.paymaya.com.

so, there is another way on generating API keys for production right?

**Comment by aceraven777** [comment]
@kdwight , okay, do you have an account with paymaya? I'm guessing the production keys is in here: https://manager.paymaya.com/

**Comment by kaiserdwight** [comment]
okay, now I think thats the issue, because the account given to me was for [https://manager-sandbox.paymaya.com/](https://manager-sandbox.paymaya.com/ )

Well, Thank you for the cooperation and fast response. I also want to suggest adding a retrieveVoidInfo because as of now there's only retrieveRefundInfo on you CheckoutAPIManager.

[https://s3-us-west-2.amazonaws.com/developers.paymaya.com.pg/payment-vault/paymentvault.html#void-void-endpoints-get-1](https://s3-us-west-2.amazonaws.com/developers.paymaya.com.pg/payment-vault/paymentvault.html#void-void-endpoints-get-1)
