### ISSUE TITLE
Wallet Payment

### ISSUE THREAD

**Issue by sm2x** [aceraven777/laravel-paymaya#17]
Is "Pay with Paymaya" to accept wallet payment supported (can handle and accept PayMaya, GCash, QRph)

![image](https://user-images.githubusercontent.com/6595333/122922899-af07a100-d396-11eb-8fcd-5640e662b58b.png)

**Comment by aceraven777** [comment]
Hi @sm2x, were not the official PayMaya customer service. We can only answer technical questions about the repository.

You can go to the official paymaya website: https://www.paymaya.com/. If you want to chat with a customer service, there's a live chat there.

**Comment by sm2x** [comment]
yes I'm aware of that, but you specifically ported to work this on Laravel
by any chance, you can extend your work to adapt "Pay with Paymaya"
as a token of appreciation, I will donate on your Paypal, please consider.

**Comment by aceraven777** [comment]
Oh I see, Ill take a look at this after my working hours.

**Comment by sm2x** [comment]
looking forward to, appreciated

**Comment by aceraven777** [comment]
Hi @sm2x, I played around with the PayMaya checkout API. I cannot find how to turn on the "Pay with Paymaya" button. So I created an issue to the official PayMaya PHP SDK https://github.com/PayMaya/PayMaya-PHP-SDK/issues/28.

The representative said that you have to contact your Account Manager to enable this feature. When enabled, the button will automatically show at the checkout page.

**Comment by sm2x** [comment]
oh, let me work on the Account and will let you know once its activated so we'll confirm this,
Thank you.

**Comment by aceraven777** [comment]
Happy to help :)
