### ISSUE TITLE
Maintainability

### ISSUE THREAD

**Issue by janehernandez** [aceraven777/laravel-paymaya#18]
Hi, I have a question, how long will this package be maintainable? Thank you.

**Comment by aceraven777** [comment]
Hi @janehernandez, I will try to maintain this package as long as I can.

This package will work as long as Paymaya Dev doesn't change/remove any APIs on their end.

If you want to contribute on this package (like add a functionality), you may trigger a pull request.

**Comment by camayacoast** [comment]
hi is this package still maintanable? thank you

**Comment by aceraven777** [comment]
Hi @camayacoast , as I stated above, I will try to maintain this package as long as I can.

This is open source, anyone can trigger a pull request if they want additional functionality.
