### ISSUE TITLE
different logo shown in paymaya gateway

### ISSUE THREAD

**Issue by chiJhay** [aceraven777/laravel-paymaya#21]
Why is the logo in paymaya gateway is different from ours? Even i already customized it.
![Paymaya  SS1](https://user-images.githubusercontent.com/110532981/203721781-eb4c2e24-590e-45ab-af17-c524d37db4dc.png)
![paymaya SS](https://user-images.githubusercontent.com/110532981/203721890-05a51d75-ae65-4df8-b090-bfd8e8928bfd.png)

**Comment by aceraven777** [comment]
What API keys are you using? Are you using any API keys found here: https://developers.maya.ph/reference/sandbox-credentials-and-cards#sandbox-api-keys

**Comment by aceraven777** [comment]
Take note that the API Keys here are **PUBLIC**: https://developers.maya.ph/reference/sandbox-credentials-and-cards#sandbox-api-keys

Anyone can use the API keys there and change the shop customization.

Did you already contact Maya and created your own developer account? If you have your own developer account Maya will give you your own Production API Keys and Sandbox API keys.

**Comment by aceraven777** [comment]
Since there's no response, I will now close this issue .
