### ISSUE TITLE
Checkout doesn't return checkout ID

### ISSUE THREAD

**Issue by iamkenken** [aceraven777/laravel-paymaya#5]
the execute function has an error, it says that there is no checkoutID

**Comment by iamkenken** [comment]
I found out that the paymaya returned an error that says 

{"code":"2553","message":"Missing/invalid parameters.","parameters":[{"description":"quantity must be a string","field":"items[0].quantity"}]}"

but in docs it is not mandatory.

**Comment by aceraven777** [comment]
Hi @iamkenken,

Seems that they make it required in the Paymaya API and their documentation is not updated. Will create an issue to PayMaya API..

**Comment by iamkenken** [comment]
Thanks for the response aceraven777, hope it will resolve soon.

I tried to add a quantity but it returned another error from paymaya says "Please contact your system administrator"

**Comment by aceraven777** [comment]
Yup, seen that, that's what I reported here: https://github.com/PayMaya/PayMaya-PHP-SDK/issues/14

Will get back to you once resolved.

**Comment by iamkenken** [comment]
Cool! Thanks much

**Comment by aceraven777** [comment]
Hi @iamkenken,

Seems that PayMaya already fixed the issue, kindly check on your end.

Also please run `composer update`, I fixed some bugs in Webhook class

**Comment by iamkenken** [comment]
Thanks, yeah it was fixed when I checked it last month but today, the error came back.

**Comment by aceraven777** [comment]
Hi, tested this on my end, it is working. Can you share your code here?

What API keys are you using?

I'm using

```
PUBLIC_API_KEY=pk-lNAUk1jk7VPnf7koOT1uoGJoZJjmAxrbjpj6urB8EIA
SECRET_API_KEY=sk-fzukI3GXrzNIUyvXY3n16cji8VTJITfzylz5o5QzZMC
```
