### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by ghost** [aceraven777/laravel-paymaya#7]
Error in creating the webhooks. In Webhook.php line 42 I get error **Invalid argument supplied for foreach()** I don't know how to fix this, last Friday I check the package it's working but now, I don't know why it getting me an error.

`[2020-03-16 13:33:12] local.ERROR: Invalid argument supplied for foreach() {"userId":1,"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /var/www/html/projects/project_name/vendor/aceraven777/laravel-paymaya/src/API/Webhook.php:42)`

**Comment by ghost** [comment]
> Error in creating the webhooks. In Webhook.php line 42 I get error **Invalid argument supplied for foreach()** I don't know how to fix this, last Friday I check the package it's working but now, I don't know why it getting me an error.
> 
> `[2020-03-16 13:33:12] local.ERROR: Invalid argument supplied for foreach() {"userId":1,"exception":"[object] (ErrorException(code: 0): Invalid argument supplied for foreach() at /var/www/html/projects/project_name/vendor/aceraven777/laravel-paymaya/src/API/Webhook.php:42)`

Already working now. I need to install it again but I don't know why.

**Comment by aceraven777** [comment]
@baqueroglenncarlo , I think there's something wrong in the Paymaya API call at that time.
