### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by anestores** [aceraven777/laravel-paymaya#8]
Hi, I tried installing this today but encountered error below:

Laravel version: 7.10.3
PHP version: 7.4.3

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for psr/log (locked at 1.1.3) -> satisfiable by psr/log[1.1.3].
    - aceraven777/laravel-paymaya v1.0.0 requires psr/log 1.0.2 -> satisfiable by psr/log[1.0.2].
    - aceraven777/laravel-paymaya v1.0.1 requires psr/log 1.0.2 -> satisfiable by psr/log[1.0.2].
    - aceraven777/laravel-paymaya v1.0.2 requires psr/log 1.0.2 -> satisfiable by psr/log[1.0.2].
    - aceraven777/laravel-paymaya v1.0.3 requires psr/log 1.0.2 -> satisfiable by psr/log[1.0.2].
    - Conclusion: don't install psr/log 1.0.2
    - Installation request for aceraven777/laravel-paymaya ^1.0 -> satisfiable by aceraven777/laravel-paymaya[v1.0.0, v1.0.1, v1.0.2, v1.0.3].

**Comment by aceraven777** [comment]
I removed `psr/log` from composer. Kindly install the package again :)

**Comment by aceraven777** [comment]
Hi, I removed `psr/log` from the composer. Kindly install the package again :)
